// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sismog.Context;

#nullable disable

namespace Sismog.Migrations
{
    [DbContext(typeof(InfiniteContext))]
    [Migration("20251116210437_1.0.0")]
    partial class _100
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sismog.Models.Bairro", b =>
                {
                    b.Property<long>("IdBairro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_bairro");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdBairro"));

                    b.Property<long?>("Codigo")
                        .HasColumnType("bigint")
                        .HasColumnName("codigo");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("IdBairro");

                    b.ToTable("bairro", "cadastro");
                });

            modelBuilder.Entity("Sismog.Models.BaixaEstoque", b =>
                {
                    b.Property<long>("IdBaixaEstoque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_baixa_estoque");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdBaixaEstoque"));

                    b.Property<bool>("Baixado")
                        .HasColumnType("boolean")
                        .HasColumnName("baixado");

                    b.Property<long>("IdEstoque")
                        .HasColumnType("bigint")
                        .HasColumnName("id_estoque");

                    b.Property<long>("IdPedido")
                        .HasColumnType("bigint")
                        .HasColumnName("id_pedido");

                    b.Property<long>("IdProduto")
                        .HasColumnType("bigint")
                        .HasColumnName("id_produto");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.HasKey("IdBaixaEstoque");

                    b.HasIndex("IdEstoque");

                    b.HasIndex("IdPedido");

                    b.HasIndex("IdProduto");

                    b.ToTable("baixa_estoque", "estoques");
                });

            modelBuilder.Entity("Sismog.Models.Cidade", b =>
                {
                    b.Property<long>("IdCidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_cidade");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdCidade"));

                    b.Property<long?>("Codigo")
                        .HasColumnType("bigint")
                        .HasColumnName("codigo");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("IdCidade");

                    b.ToTable("cidade", "cadastro");
                });

            modelBuilder.Entity("Sismog.Models.Cliente", b =>
                {
                    b.Property<long?>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_cliente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long?>("IdCliente"));

                    b.Property<DateTime?>("ClienteDesde")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cliente_desde");

                    b.Property<string>("Cpf")
                        .HasColumnType("text")
                        .HasColumnName("cpf");

                    b.Property<long?>("Idade")
                        .HasColumnType("bigint")
                        .HasColumnName("idade");

                    b.Property<DateTime?>("Nascimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("nascimento");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("ObservacaoCliente")
                        .HasColumnType("text")
                        .HasColumnName("observacao_cliente");

                    b.Property<string>("Rg")
                        .HasColumnType("text")
                        .HasColumnName("rg");

                    b.Property<string>("Sexo")
                        .HasColumnType("text")
                        .HasColumnName("sexo");

                    b.Property<long?>("Tipo")
                        .HasColumnType("bigint")
                        .HasColumnName("tipo");

                    b.HasKey("IdCliente");

                    b.ToTable("cliente", "cadastro");
                });

            modelBuilder.Entity("Sismog.Models.Email", b =>
                {
                    b.Property<long>("IdEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_email");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdEmail"));

                    b.Property<string>("Endereco")
                        .HasColumnType("text")
                        .HasColumnName("endereco");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cliente");

                    b.HasKey("IdEmail");

                    b.HasIndex("IdCliente");

                    b.ToTable("email", "cadastro");
                });

            modelBuilder.Entity("Sismog.Models.Endereco", b =>
                {
                    b.Property<long>("IdEndereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_endereco");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdEndereco"));

                    b.Property<long?>("Bairro")
                        .HasColumnType("bigint")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasColumnType("text")
                        .HasColumnName("cep");

                    b.Property<long?>("Cidade")
                        .HasColumnType("bigint")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .HasColumnType("text")
                        .HasColumnName("complemento");

                    b.Property<long?>("Estado")
                        .HasColumnType("bigint")
                        .HasColumnName("estado");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cliente");

                    b.Property<string>("Logradouro")
                        .HasColumnType("text")
                        .HasColumnName("logradouro");

                    b.Property<string>("Numero")
                        .HasColumnType("text")
                        .HasColumnName("numero");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<string>("PontoReferencia")
                        .HasColumnType("text")
                        .HasColumnName("ponto_referencia");

                    b.HasKey("IdEndereco");

                    b.HasIndex("IdCliente");

                    b.ToTable("endereco", "cadastro");
                });

            modelBuilder.Entity("Sismog.Models.Entradum", b =>
                {
                    b.Property<long>("IdEntrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_entrada");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdEntrada"));

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<long>("NumeroEntrada")
                        .HasColumnType("bigint")
                        .HasColumnName("numero_entrada");

                    b.Property<long>("Responsavel")
                        .HasColumnType("bigint")
                        .HasColumnName("responsavel");

                    b.HasKey("IdEntrada");

                    b.ToTable("entrada", "produtos");
                });

            modelBuilder.Entity("Sismog.Models.Estado", b =>
                {
                    b.Property<long>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_estado");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdEstado"));

                    b.Property<long?>("Codigo")
                        .HasColumnType("bigint")
                        .HasColumnName("codigo");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("IdEstado");

                    b.ToTable("estado", "cadastro");
                });

            modelBuilder.Entity("Sismog.Models.Estoque", b =>
                {
                    b.Property<long>("IdEstoque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_estoque");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdEstoque"));

                    b.Property<string>("NomeEstoque")
                        .HasColumnType("text")
                        .HasColumnName("nome_estoque");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<decimal?>("QtdAtual")
                        .HasColumnType("numeric")
                        .HasColumnName("qtd_atual");

                    b.Property<decimal?>("QtdMaxima")
                        .HasColumnType("numeric")
                        .HasColumnName("qtd_maxima");

                    b.Property<decimal?>("QtdMinima")
                        .HasColumnType("numeric")
                        .HasColumnName("qtd_minima");

                    b.HasKey("IdEstoque");

                    b.ToTable("estoque", "estoques");
                });

            modelBuilder.Entity("Sismog.Models.ItemPedido", b =>
                {
                    b.Property<long>("IdItemPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_item_pedido");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdItemPedido"));

                    b.Property<decimal>("Desconto")
                        .HasColumnType("numeric")
                        .HasColumnName("desconto");

                    b.Property<long?>("IdLote")
                        .HasColumnType("bigint")
                        .HasColumnName("id_lote");

                    b.Property<long>("IdPedido")
                        .HasColumnType("bigint")
                        .HasColumnName("id_pedido");

                    b.Property<long>("Item")
                        .HasColumnType("bigint")
                        .HasColumnName("item");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("numeric")
                        .HasColumnName("preco_unitario");

                    b.Property<long>("Quantidade")
                        .HasColumnType("bigint")
                        .HasColumnName("quantidade");

                    b.HasKey("IdItemPedido");

                    b.HasIndex("IdPedido");

                    b.ToTable("item_pedido", "pedidos");
                });

            modelBuilder.Entity("Sismog.Models.ItemVersaoOrcamento", b =>
                {
                    b.Property<long>("IdItemVersaoOrcamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_item_versao_orcamento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdItemVersaoOrcamento"));

                    b.Property<decimal>("Desconto")
                        .HasColumnType("numeric")
                        .HasColumnName("desconto");

                    b.Property<long?>("IdLote")
                        .HasColumnType("bigint")
                        .HasColumnName("id_lote");

                    b.Property<long>("IdVersaoOrcamento")
                        .HasColumnType("bigint")
                        .HasColumnName("id_versao_orcamento");

                    b.Property<long>("Item")
                        .HasColumnType("bigint")
                        .HasColumnName("item");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("numeric")
                        .HasColumnName("preco_unitario");

                    b.Property<long>("Quantidade")
                        .HasColumnType("bigint")
                        .HasColumnName("quantidade");

                    b.HasKey("IdItemVersaoOrcamento");

                    b.HasIndex("IdVersaoOrcamento");

                    b.ToTable("item_versao_orcamento", "orcamentos");
                });

            modelBuilder.Entity("Sismog.Models.LoteEntradum", b =>
                {
                    b.Property<long>("IdLoteEntrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_lote_entrada");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdLoteEntrada"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<long>("IdEntrada")
                        .HasColumnType("bigint")
                        .HasColumnName("id_entrada");

                    b.Property<string>("NomeLoteEntrada")
                        .HasColumnType("text")
                        .HasColumnName("nome_lote_entrada");

                    b.Property<long>("NumeroLoteEntrada")
                        .HasColumnType("bigint")
                        .HasColumnName("numero_lote_entrada");

                    b.Property<long>("Responsavel")
                        .HasColumnType("bigint")
                        .HasColumnName("responsavel");

                    b.Property<long?>("TipoProduto")
                        .HasColumnType("bigint")
                        .HasColumnName("tipo_produto");

                    b.HasKey("IdLoteEntrada");

                    b.HasIndex("IdEntrada");

                    b.ToTable("lote_entrada", "produtos");
                });

            modelBuilder.Entity("Sismog.Models.LoteEstoque", b =>
                {
                    b.Property<long>("IdLoteEstoque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_lote_estoque");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdLoteEstoque"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<long>("IdEstoque")
                        .HasColumnType("bigint")
                        .HasColumnName("id_estoque");

                    b.Property<string>("NomeLoteEstoque")
                        .HasColumnType("text")
                        .HasColumnName("nome_lote_estoque");

                    b.Property<long>("NumeroLoteEstoque")
                        .HasColumnType("bigint")
                        .HasColumnName("numero_lote_estoque");

                    b.Property<long>("Responsavel")
                        .HasColumnType("bigint")
                        .HasColumnName("responsavel");

                    b.Property<long?>("TipoProduto")
                        .HasColumnType("bigint")
                        .HasColumnName("tipo_produto");

                    b.HasKey("IdLoteEstoque");

                    b.HasIndex("IdEstoque");

                    b.ToTable("lote_estoque", "produtos");
                });

            modelBuilder.Entity("Sismog.Models.MeioDeConhecimento", b =>
                {
                    b.Property<long>("IdMeioDeConhecimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_meio_de_conhecimento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdMeioDeConhecimento"));

                    b.Property<string>("Motivo")
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.HasKey("IdMeioDeConhecimento");

                    b.ToTable("meio_de_conhecimento", "cadastro");
                });

            modelBuilder.Entity("Sismog.Models.Orcamento", b =>
                {
                    b.Property<long?>("IdOrcamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_orcamento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long?>("IdOrcamento"));

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<long?>("Entrega")
                        .HasColumnType("bigint")
                        .HasColumnName("entrega");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cliente");

                    b.Property<long?>("MeioDeConhecimento")
                        .HasColumnType("bigint")
                        .HasColumnName("meio_de_conhecimento");

                    b.Property<long?>("NumeroOrcamento")
                        .HasColumnType("bigint")
                        .HasColumnName("numero_orcamento");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<long?>("Retirada")
                        .HasColumnType("bigint")
                        .HasColumnName("retirada");

                    b.Property<long?>("Situacao")
                        .HasColumnType("bigint")
                        .HasColumnName("situacao");

                    b.HasKey("IdOrcamento");

                    b.ToTable("orcamento", "orcamentos");
                });

            modelBuilder.Entity("Sismog.Models.Pedido", b =>
                {
                    b.Property<long>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_pedido");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdPedido"));

                    b.Property<decimal?>("Acrescimo")
                        .HasColumnType("numeric")
                        .HasColumnName("acrescimo");

                    b.Property<DateOnly?>("DataCriacao")
                        .HasColumnType("date")
                        .HasColumnName("data_criacao");

                    b.Property<decimal?>("Desconto")
                        .HasColumnType("numeric")
                        .HasColumnName("desconto");

                    b.Property<long?>("Entrega")
                        .HasColumnType("bigint")
                        .HasColumnName("entrega");

                    b.Property<long?>("FormaDePagamento")
                        .HasColumnType("bigint")
                        .HasColumnName("forma_de_pagamento");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cliente");

                    b.Property<long>("IdOrcamento")
                        .HasColumnType("bigint")
                        .HasColumnName("id_orcamento");

                    b.Property<long>("IdVersaoOrcamento")
                        .HasColumnType("bigint")
                        .HasColumnName("id_versao_orcamento");

                    b.Property<long?>("Retirada")
                        .HasColumnType("bigint")
                        .HasColumnName("retirada");

                    b.Property<long?>("Situacao")
                        .HasColumnType("bigint")
                        .HasColumnName("situacao");

                    b.Property<decimal?>("Subtotal")
                        .HasColumnType("numeric")
                        .HasColumnName("subtotal");

                    b.Property<decimal?>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.Property<decimal?>("ValorEntrega")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_entrega");

                    b.Property<decimal?>("ValorProdutos")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_produtos");

                    b.HasKey("IdPedido");

                    b.ToTable("pedido", "pedidos");
                });

            modelBuilder.Entity("Sismog.Models.Produto", b =>
                {
                    b.Property<long>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_produto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdProduto"));

                    b.Property<decimal?>("Altura")
                        .HasColumnType("numeric")
                        .HasColumnName("altura");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("NomeProduto")
                        .HasColumnType("text")
                        .HasColumnName("nome_produto");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("numeric")
                        .HasColumnName("peso");

                    b.Property<decimal?>("PrecoAtacado")
                        .HasColumnType("numeric")
                        .HasColumnName("preco_atacado");

                    b.Property<decimal?>("PrecoCusto")
                        .HasColumnType("numeric")
                        .HasColumnName("preco_custo");

                    b.Property<decimal?>("PrecoVarejo")
                        .HasColumnType("numeric")
                        .HasColumnName("preco_varejo");

                    b.Property<long?>("Tipo")
                        .HasColumnType("bigint")
                        .HasColumnName("tipo");

                    b.Property<long?>("Unidades")
                        .HasColumnType("bigint")
                        .HasColumnName("unidades");

                    b.HasKey("IdProduto");

                    b.ToTable("produto", "produtos");
                });

            modelBuilder.Entity("Sismog.Models.ProdutoEntradum", b =>
                {
                    b.Property<long>("IdProdutoEntrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_produto_entrada");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdProdutoEntrada"));

                    b.Property<long>("IdEntrada")
                        .HasColumnType("bigint")
                        .HasColumnName("id_entrada");

                    b.Property<long>("IdLote")
                        .HasColumnType("bigint")
                        .HasColumnName("id_lote");

                    b.Property<long>("IdProduto")
                        .HasColumnType("bigint")
                        .HasColumnName("id_produto");

                    b.Property<long>("Quantidade")
                        .HasColumnType("bigint")
                        .HasColumnName("quantidade");

                    b.HasKey("IdProdutoEntrada");

                    b.HasIndex("IdEntrada");

                    b.HasIndex("IdProduto")
                        .IsUnique();

                    b.ToTable("produto_entrada", "produtos");
                });

            modelBuilder.Entity("Sismog.Models.ProdutoEstoque", b =>
                {
                    b.Property<long>("IdProdutoEstoque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_produto_estoque");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdProdutoEstoque"));

                    b.Property<long>("IdEstoque")
                        .HasColumnType("bigint")
                        .HasColumnName("id_estoque");

                    b.Property<long>("IdProduto")
                        .HasColumnType("bigint")
                        .HasColumnName("id_produto");

                    b.Property<long>("Quantidade")
                        .HasColumnType("bigint")
                        .HasColumnName("quantidade");

                    b.HasKey("IdProdutoEstoque");

                    b.HasIndex("IdEstoque");

                    b.HasIndex("IdProduto");

                    b.ToTable("produto_estoque", "produtos");
                });

            modelBuilder.Entity("Sismog.Models.Situacao", b =>
                {
                    b.Property<long>("IdSituacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_situacao");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdSituacao"));

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("IdSituacao");

                    b.ToTable("situacao", "info");
                });

            modelBuilder.Entity("Sismog.Models.Sms", b =>
                {
                    b.Property<long>("IdSms")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_sms");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdSms"));

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cliente");

                    b.Property<string>("Numero")
                        .HasColumnType("text")
                        .HasColumnName("numero");

                    b.HasKey("IdSms");

                    b.HasIndex("IdCliente");

                    b.ToTable("sms", "cadastro");
                });

            modelBuilder.Entity("Sismog.Models.Telefone", b =>
                {
                    b.Property<long>("IdTelefone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_telefone");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdTelefone"));

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cliente");

                    b.Property<string>("Numero")
                        .HasColumnType("text")
                        .HasColumnName("numero");

                    b.HasKey("IdTelefone");

                    b.HasIndex("IdCliente");

                    b.ToTable("telefone", "cadastro");
                });

            modelBuilder.Entity("Sismog.Models.Telegram", b =>
                {
                    b.Property<long>("IdTelegram")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_telegram");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdTelegram"));

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cliente");

                    b.Property<string>("Numero")
                        .HasColumnType("text")
                        .HasColumnName("numero");

                    b.HasKey("IdTelegram");

                    b.HasIndex("IdCliente");

                    b.ToTable("telegram", "cadastro");
                });

            modelBuilder.Entity("Sismog.Models.VersaoOrcamento", b =>
                {
                    b.Property<long?>("IdVersaoOrcamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_versao_orcamento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long?>("IdVersaoOrcamento"));

                    b.Property<decimal?>("Acrescimo")
                        .HasColumnType("numeric")
                        .HasColumnName("acrescimo");

                    b.Property<DateOnly?>("DataCriacao")
                        .HasColumnType("date")
                        .HasColumnName("data_criacao");

                    b.Property<decimal?>("Desconto")
                        .HasColumnType("numeric")
                        .HasColumnName("desconto");

                    b.Property<long?>("Entrega")
                        .HasColumnType("bigint")
                        .HasColumnName("entrega");

                    b.Property<long?>("FormaDePagamento")
                        .HasColumnType("bigint")
                        .HasColumnName("forma_de_pagamento");

                    b.Property<long?>("IdOrcamento")
                        .HasColumnType("bigint")
                        .HasColumnName("id_orcamento");

                    b.Property<string>("NomeVersaoOrcamento")
                        .HasColumnType("text")
                        .HasColumnName("nome_versao_orcamento");

                    b.Property<long?>("NumeroVersaoOrcamento")
                        .HasColumnType("bigint")
                        .HasColumnName("numero_versao_orcamento");

                    b.Property<long?>("Retirada")
                        .HasColumnType("bigint")
                        .HasColumnName("retirada");

                    b.Property<long?>("Situacao")
                        .HasColumnType("bigint")
                        .HasColumnName("situacao");

                    b.Property<decimal?>("Subtotal")
                        .HasColumnType("numeric")
                        .HasColumnName("subtotal");

                    b.Property<decimal?>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.Property<decimal?>("ValorEntrega")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_entrega");

                    b.Property<decimal?>("ValorItens")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_itens");

                    b.HasKey("IdVersaoOrcamento");

                    b.HasIndex("IdOrcamento");

                    b.ToTable("versao_orcamento", "orcamentos");
                });

            modelBuilder.Entity("Sismog.Models.Whatsapp", b =>
                {
                    b.Property<long>("IdWhatsapp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_whatsapp");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdWhatsapp"));

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cliente");

                    b.Property<string>("Numero")
                        .HasColumnType("text")
                        .HasColumnName("numero");

                    b.HasKey("IdWhatsapp");

                    b.HasIndex("IdCliente");

                    b.ToTable("whatsapp", "cadastro");
                });

            modelBuilder.Entity("Sismog.Models.BaixaEstoque", b =>
                {
                    b.HasOne("Sismog.Models.Estoque", null)
                        .WithMany()
                        .HasForeignKey("IdEstoque")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sismog.Models.Pedido", null)
                        .WithMany()
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sismog.Models.Produto", null)
                        .WithMany()
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sismog.Models.Email", b =>
                {
                    b.HasOne("Sismog.Models.Cliente", "IdClienteNavigation")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdClienteNavigation");
                });

            modelBuilder.Entity("Sismog.Models.Endereco", b =>
                {
                    b.HasOne("Sismog.Models.Cliente", "IdClienteNavigation")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdClienteNavigation");
                });

            modelBuilder.Entity("Sismog.Models.ItemPedido", b =>
                {
                    b.HasOne("Sismog.Models.Pedido", "IdPedidoNavigation")
                        .WithMany("ItemPedidos")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdPedidoNavigation");
                });

            modelBuilder.Entity("Sismog.Models.ItemVersaoOrcamento", b =>
                {
                    b.HasOne("Sismog.Models.VersaoOrcamento", "IdVersaoOrcamentoNavigation")
                        .WithMany("ItemVersaoOrcamentos")
                        .HasForeignKey("IdVersaoOrcamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdVersaoOrcamentoNavigation");
                });

            modelBuilder.Entity("Sismog.Models.LoteEntradum", b =>
                {
                    b.HasOne("Sismog.Models.Entradum", "IdEntradaNavigation")
                        .WithMany("LoteEntrada")
                        .HasForeignKey("IdEntrada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdEntradaNavigation");
                });

            modelBuilder.Entity("Sismog.Models.LoteEstoque", b =>
                {
                    b.HasOne("Sismog.Models.Estoque", "IdEstoqueNavigation")
                        .WithMany("LoteEstoques")
                        .HasForeignKey("IdEstoque")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdEstoqueNavigation");
                });

            modelBuilder.Entity("Sismog.Models.ProdutoEntradum", b =>
                {
                    b.HasOne("Sismog.Models.Entradum", "IdEntradaNavigation")
                        .WithMany("ProdutoEntrada")
                        .HasForeignKey("IdEntrada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sismog.Models.Produto", "IdProdutoNavigation")
                        .WithOne("ProdutoEntradum")
                        .HasForeignKey("Sismog.Models.ProdutoEntradum", "IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdEntradaNavigation");

                    b.Navigation("IdProdutoNavigation");
                });

            modelBuilder.Entity("Sismog.Models.ProdutoEstoque", b =>
                {
                    b.HasOne("Sismog.Models.Estoque", "IdEstoqueNavigation")
                        .WithMany("ProdutoEstoques")
                        .HasForeignKey("IdEstoque")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sismog.Models.Produto", "IdProdutoNavigation")
                        .WithMany("ProdutoEstoques")
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdEstoqueNavigation");

                    b.Navigation("IdProdutoNavigation");
                });

            modelBuilder.Entity("Sismog.Models.Sms", b =>
                {
                    b.HasOne("Sismog.Models.Cliente", "IdClienteNavigation")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdClienteNavigation");
                });

            modelBuilder.Entity("Sismog.Models.Telefone", b =>
                {
                    b.HasOne("Sismog.Models.Cliente", "IdClienteNavigation")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdClienteNavigation");
                });

            modelBuilder.Entity("Sismog.Models.Telegram", b =>
                {
                    b.HasOne("Sismog.Models.Cliente", "IdClienteNavigation")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdClienteNavigation");
                });

            modelBuilder.Entity("Sismog.Models.VersaoOrcamento", b =>
                {
                    b.HasOne("Sismog.Models.Orcamento", "IdOrcamentoNavigation")
                        .WithMany("VersaoOrcamentos")
                        .HasForeignKey("IdOrcamento");

                    b.Navigation("IdOrcamentoNavigation");
                });

            modelBuilder.Entity("Sismog.Models.Whatsapp", b =>
                {
                    b.HasOne("Sismog.Models.Cliente", "IdClienteNavigation")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdClienteNavigation");
                });

            modelBuilder.Entity("Sismog.Models.Entradum", b =>
                {
                    b.Navigation("LoteEntrada");

                    b.Navigation("ProdutoEntrada");
                });

            modelBuilder.Entity("Sismog.Models.Estoque", b =>
                {
                    b.Navigation("LoteEstoques");

                    b.Navigation("ProdutoEstoques");
                });

            modelBuilder.Entity("Sismog.Models.Orcamento", b =>
                {
                    b.Navigation("VersaoOrcamentos");
                });

            modelBuilder.Entity("Sismog.Models.Pedido", b =>
                {
                    b.Navigation("ItemPedidos");
                });

            modelBuilder.Entity("Sismog.Models.Produto", b =>
                {
                    b.Navigation("ProdutoEntradum");

                    b.Navigation("ProdutoEstoques");
                });

            modelBuilder.Entity("Sismog.Models.VersaoOrcamento", b =>
                {
                    b.Navigation("ItemVersaoOrcamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
