BEGIN;


CREATE TABLE IF NOT EXISTS cadastro.bairro
(
    id_bairro bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nome text COLLATE pg_catalog."default",
    codigo bigint,
    CONSTRAINT "PK_bairro" PRIMARY KEY (id_bairro)
);

CREATE TABLE IF NOT EXISTS cadastro.cidade
(
    id_cidade bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nome text COLLATE pg_catalog."default",
    codigo bigint,
    CONSTRAINT "PK_cidade" PRIMARY KEY (id_cidade)
);

CREATE TABLE IF NOT EXISTS cadastro.cliente
(
    id_cliente bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nome text COLLATE pg_catalog."default",
    cpf text COLLATE pg_catalog."default",
    rg text COLLATE pg_catalog."default",
    tipo bigint,
    nascimento timestamp with time zone,
    idade bigint,
    sexo text COLLATE pg_catalog."default",
    cliente_desde timestamp with time zone,
    observacao_cliente text COLLATE pg_catalog."default",
    CONSTRAINT "PK_cliente" PRIMARY KEY (id_cliente)
);

CREATE TABLE IF NOT EXISTS cadastro.email
(
    id_email bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    endereco text COLLATE pg_catalog."default",
    id_cliente bigint NOT NULL,
    CONSTRAINT "PK_email" PRIMARY KEY (id_email)
);

CREATE TABLE IF NOT EXISTS cadastro.endereco
(
    id_endereco bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_cliente bigint NOT NULL,
    logradouro text COLLATE pg_catalog."default",
    cep text COLLATE pg_catalog."default",
    numero text COLLATE pg_catalog."default",
    bairro bigint,
    cidade bigint,
    estado bigint,
    complemento text COLLATE pg_catalog."default",
    ponto_referencia text COLLATE pg_catalog."default",
    observacao text COLLATE pg_catalog."default",
    CONSTRAINT "PK_endereco" PRIMARY KEY (id_endereco)
);

CREATE TABLE IF NOT EXISTS cadastro.estado
(
    id_estado bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nome text COLLATE pg_catalog."default",
    codigo bigint,
    CONSTRAINT "PK_estado" PRIMARY KEY (id_estado)
);

CREATE TABLE IF NOT EXISTS cadastro.meio_de_conhecimento
(
    id_meio_de_conhecimento bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    motivo text COLLATE pg_catalog."default",
    CONSTRAINT "PK_meio_de_conhecimento" PRIMARY KEY (id_meio_de_conhecimento)
);

CREATE TABLE IF NOT EXISTS cadastro.sms
(
    id_sms bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    numero text COLLATE pg_catalog."default",
    id_cliente bigint NOT NULL,
    CONSTRAINT "PK_sms" PRIMARY KEY (id_sms)
);

CREATE TABLE IF NOT EXISTS cadastro.telefone
(
    id_telefone bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    numero text COLLATE pg_catalog."default",
    id_cliente bigint NOT NULL,
    CONSTRAINT "PK_telefone" PRIMARY KEY (id_telefone)
);

CREATE TABLE IF NOT EXISTS cadastro.telegram
(
    id_telegram bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    numero text COLLATE pg_catalog."default",
    id_cliente bigint NOT NULL,
    CONSTRAINT "PK_telegram" PRIMARY KEY (id_telegram)
);

CREATE TABLE IF NOT EXISTS cadastro.whatsapp
(
    id_whatsapp bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    numero text COLLATE pg_catalog."default",
    id_cliente bigint NOT NULL,
    CONSTRAINT "PK_whatsapp" PRIMARY KEY (id_whatsapp)
);

CREATE TABLE IF NOT EXISTS estoques.baixa_estoque
(
    id_baixa_estoque bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_produto bigint NOT NULL,
    id_estoque bigint NOT NULL,
    id_pedido bigint NOT NULL,
    quantidade integer NOT NULL,
    baixado boolean NOT NULL,
    CONSTRAINT "PK_baixa_estoque" PRIMARY KEY (id_baixa_estoque)
);

CREATE TABLE IF NOT EXISTS estoques.estoque
(
    id_estoque bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nome_estoque text COLLATE pg_catalog."default",
    qtd_minima numeric,
    qtd_atual numeric,
    qtd_maxima numeric,
    observacao text COLLATE pg_catalog."default",
    CONSTRAINT "PK_estoque" PRIMARY KEY (id_estoque)
);

CREATE TABLE IF NOT EXISTS info.situacao
(
    id_situacao bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nome text COLLATE pg_catalog."default",
    CONSTRAINT "PK_situacao" PRIMARY KEY (id_situacao)
);

CREATE TABLE IF NOT EXISTS migrations."__EFMigrationsHistory_Sismog"
(
    "MigrationId" character varying(150) COLLATE pg_catalog."default" NOT NULL,
    "ProductVersion" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory_Sismog" PRIMARY KEY ("MigrationId")
);

CREATE TABLE IF NOT EXISTS orcamentos.item_versao_orcamento
(
    id_item_versao_orcamento bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    item bigint NOT NULL,
    id_versao_orcamento bigint NOT NULL,
    quantidade bigint NOT NULL,
    id_lote bigint,
    preco_unitario numeric NOT NULL,
    desconto numeric NOT NULL,
    CONSTRAINT "PK_item_versao_orcamento" PRIMARY KEY (id_item_versao_orcamento)
);

CREATE TABLE IF NOT EXISTS orcamentos.orcamento
(
    id_orcamento bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    numero_orcamento bigint,
    id_cliente bigint NOT NULL,
    data_criacao timestamp with time zone,
    entrega bigint,
    retirada bigint,
    situacao bigint,
    observacao text COLLATE pg_catalog."default",
    meio_de_conhecimento bigint,
    CONSTRAINT "PK_orcamento" PRIMARY KEY (id_orcamento)
);

CREATE TABLE IF NOT EXISTS orcamentos.versao_orcamento
(
    id_versao_orcamento bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    numero_versao_orcamento bigint,
    nome_versao_orcamento text COLLATE pg_catalog."default",
    id_orcamento bigint,
    entrega bigint,
    retirada bigint,
    valor_itens numeric,
    valor_entrega numeric,
    desconto numeric,
    acrescimo numeric,
    subtotal numeric,
    total numeric,
    forma_de_pagamento bigint,
    data_criacao date,
    situacao bigint,
    CONSTRAINT "PK_versao_orcamento" PRIMARY KEY (id_versao_orcamento)
);

CREATE TABLE IF NOT EXISTS pedidos.item_pedido
(
    id_item_pedido bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    item bigint NOT NULL,
    id_pedido bigint NOT NULL,
    quantidade bigint NOT NULL,
    id_lote bigint,
    preco_unitario numeric NOT NULL,
    desconto numeric NOT NULL,
    CONSTRAINT "PK_item_pedido" PRIMARY KEY (id_item_pedido)
);

CREATE TABLE IF NOT EXISTS pedidos.pedido
(
    id_pedido bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_orcamento bigint NOT NULL,
    id_versao_orcamento bigint NOT NULL,
    id_cliente bigint NOT NULL,
    entrega bigint,
    retirada bigint,
    valor_produtos numeric,
    valor_entrega numeric,
    desconto numeric,
    acrescimo numeric,
    subtotal numeric,
    total numeric,
    forma_de_pagamento bigint,
    data_criacao date,
    situacao bigint,
    CONSTRAINT "PK_pedido" PRIMARY KEY (id_pedido)
);

CREATE TABLE IF NOT EXISTS produtos.entrada
(
    id_entrada bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    numero_entrada bigint NOT NULL,
    data date NOT NULL,
    responsavel bigint NOT NULL,
    CONSTRAINT "PK_entrada" PRIMARY KEY (id_entrada)
);

CREATE TABLE IF NOT EXISTS produtos.lote_entrada
(
    id_lote_entrada bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nome_lote_entrada text COLLATE pg_catalog."default",
    numero_lote_entrada bigint NOT NULL,
    id_entrada bigint NOT NULL,
    descricao text COLLATE pg_catalog."default",
    tipo_produto bigint,
    responsavel bigint NOT NULL,
    CONSTRAINT "PK_lote_entrada" PRIMARY KEY (id_lote_entrada)
);

CREATE TABLE IF NOT EXISTS produtos.lote_estoque
(
    id_lote_estoque bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nome_lote_estoque text COLLATE pg_catalog."default",
    numero_lote_estoque bigint NOT NULL,
    id_estoque bigint NOT NULL,
    descricao text COLLATE pg_catalog."default",
    tipo_produto bigint,
    responsavel bigint NOT NULL,
    CONSTRAINT "PK_lote_estoque" PRIMARY KEY (id_lote_estoque)
);

CREATE TABLE IF NOT EXISTS produtos.produto
(
    id_produto bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nome_produto text COLLATE pg_catalog."default",
    descricao text COLLATE pg_catalog."default",
    unidades bigint,
    preco_custo numeric,
    preco_atacado numeric,
    preco_varejo numeric,
    tipo bigint,
    peso numeric,
    altura numeric,
    observacao text COLLATE pg_catalog."default",
    CONSTRAINT "PK_produto" PRIMARY KEY (id_produto)
);

CREATE TABLE IF NOT EXISTS produtos.produto_entrada
(
    id_produto_entrada bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_produto bigint NOT NULL,
    quantidade bigint NOT NULL,
    id_lote bigint NOT NULL,
    id_entrada bigint NOT NULL,
    CONSTRAINT "PK_produto_entrada" PRIMARY KEY (id_produto_entrada)
);

CREATE TABLE IF NOT EXISTS produtos.produto_estoque
(
    id_produto_estoque bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_produto bigint NOT NULL,
    id_estoque bigint NOT NULL,
    quantidade bigint NOT NULL,
    CONSTRAINT "PK_produto_estoque" PRIMARY KEY (id_produto_estoque)
);

ALTER TABLE IF EXISTS cadastro.email
    ADD CONSTRAINT "FK_email_cliente_id_cliente" FOREIGN KEY (id_cliente)
    REFERENCES cadastro.cliente (id_cliente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_email_id_cliente"
    ON cadastro.email(id_cliente);


ALTER TABLE IF EXISTS cadastro.endereco
    ADD CONSTRAINT "FK_endereco_cliente_id_cliente" FOREIGN KEY (id_cliente)
    REFERENCES cadastro.cliente (id_cliente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_endereco_id_cliente"
    ON cadastro.endereco(id_cliente);


ALTER TABLE IF EXISTS cadastro.sms
    ADD CONSTRAINT "FK_sms_cliente_id_cliente" FOREIGN KEY (id_cliente)
    REFERENCES cadastro.cliente (id_cliente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_sms_id_cliente"
    ON cadastro.sms(id_cliente);


ALTER TABLE IF EXISTS cadastro.telefone
    ADD CONSTRAINT "FK_telefone_cliente_id_cliente" FOREIGN KEY (id_cliente)
    REFERENCES cadastro.cliente (id_cliente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_telefone_id_cliente"
    ON cadastro.telefone(id_cliente);


ALTER TABLE IF EXISTS cadastro.telegram
    ADD CONSTRAINT "FK_telegram_cliente_id_cliente" FOREIGN KEY (id_cliente)
    REFERENCES cadastro.cliente (id_cliente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_telegram_id_cliente"
    ON cadastro.telegram(id_cliente);


ALTER TABLE IF EXISTS cadastro.whatsapp
    ADD CONSTRAINT "FK_whatsapp_cliente_id_cliente" FOREIGN KEY (id_cliente)
    REFERENCES cadastro.cliente (id_cliente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_whatsapp_id_cliente"
    ON cadastro.whatsapp(id_cliente);


ALTER TABLE IF EXISTS estoques.baixa_estoque
    ADD CONSTRAINT "FK_baixa_estoque_estoque_id_estoque" FOREIGN KEY (id_estoque)
    REFERENCES estoques.estoque (id_estoque) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_baixa_estoque_id_estoque"
    ON estoques.baixa_estoque(id_estoque);


ALTER TABLE IF EXISTS estoques.baixa_estoque
    ADD CONSTRAINT "FK_baixa_estoque_pedido_id_pedido" FOREIGN KEY (id_pedido)
    REFERENCES pedidos.pedido (id_pedido) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_baixa_estoque_id_pedido"
    ON estoques.baixa_estoque(id_pedido);


ALTER TABLE IF EXISTS estoques.baixa_estoque
    ADD CONSTRAINT "FK_baixa_estoque_produto_id_produto" FOREIGN KEY (id_produto)
    REFERENCES produtos.produto (id_produto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_baixa_estoque_id_produto"
    ON estoques.baixa_estoque(id_produto);


ALTER TABLE IF EXISTS orcamentos.item_versao_orcamento
    ADD CONSTRAINT "FK_item_versao_orcamento_versao_orcamento_id_versao_orcamento" FOREIGN KEY (id_versao_orcamento)
    REFERENCES orcamentos.versao_orcamento (id_versao_orcamento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_item_versao_orcamento_id_versao_orcamento"
    ON orcamentos.item_versao_orcamento(id_versao_orcamento);


ALTER TABLE IF EXISTS orcamentos.versao_orcamento
    ADD CONSTRAINT "FK_versao_orcamento_orcamento_id_orcamento" FOREIGN KEY (id_orcamento)
    REFERENCES orcamentos.orcamento (id_orcamento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IX_versao_orcamento_id_orcamento"
    ON orcamentos.versao_orcamento(id_orcamento);


ALTER TABLE IF EXISTS pedidos.item_pedido
    ADD CONSTRAINT "FK_item_pedido_pedido_id_pedido" FOREIGN KEY (id_pedido)
    REFERENCES pedidos.pedido (id_pedido) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_item_pedido_id_pedido"
    ON pedidos.item_pedido(id_pedido);


ALTER TABLE IF EXISTS produtos.lote_entrada
    ADD CONSTRAINT "FK_lote_entrada_entrada_id_entrada" FOREIGN KEY (id_entrada)
    REFERENCES produtos.entrada (id_entrada) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_lote_entrada_id_entrada"
    ON produtos.lote_entrada(id_entrada);


ALTER TABLE IF EXISTS produtos.lote_estoque
    ADD CONSTRAINT "FK_lote_estoque_estoque_id_estoque" FOREIGN KEY (id_estoque)
    REFERENCES estoques.estoque (id_estoque) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_lote_estoque_id_estoque"
    ON produtos.lote_estoque(id_estoque);


ALTER TABLE IF EXISTS produtos.produto_entrada
    ADD CONSTRAINT "FK_produto_entrada_entrada_id_entrada" FOREIGN KEY (id_entrada)
    REFERENCES produtos.entrada (id_entrada) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_produto_entrada_id_entrada"
    ON produtos.produto_entrada(id_entrada);


ALTER TABLE IF EXISTS produtos.produto_entrada
    ADD CONSTRAINT "FK_produto_entrada_produto_id_produto" FOREIGN KEY (id_produto)
    REFERENCES produtos.produto (id_produto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_produto_entrada_id_produto"
    ON produtos.produto_entrada(id_produto);


ALTER TABLE IF EXISTS produtos.produto_estoque
    ADD CONSTRAINT "FK_produto_estoque_estoque_id_estoque" FOREIGN KEY (id_estoque)
    REFERENCES estoques.estoque (id_estoque) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_produto_estoque_id_estoque"
    ON produtos.produto_estoque(id_estoque);


ALTER TABLE IF EXISTS produtos.produto_estoque
    ADD CONSTRAINT "FK_produto_estoque_produto_id_produto" FOREIGN KEY (id_produto)
    REFERENCES produtos.produto (id_produto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_produto_estoque_id_produto"
    ON produtos.produto_estoque(id_produto);

END;